apiVersion: apps/v1
kind: Deployment
metadata:
  name: word-emitter
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: word-emitter
  template:
    metadata:
      labels:
        app: word-emitter
    spec:
      containers:
        - name: word-emitter
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources: {{ toYaml .Values.resources | nindent 12 }}
