apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: word-emitter
  ports:
    - name: tcp
      protocol: TCP
      port: {{ .Values.service.port }}
